FROM maven:3.9-eclipse-temurin-25 AS build
WORKDIR /app
COPY pom.xml .
COPY relay-common/pom.xml ./relay-common/
COPY relay-processor/pom.xml ./relay-processor/
COPY relay-common/src ./relay-common/src
COPY relay-processor/src ./relay-processor/src
RUN mvn clean package -pl relay-processor -am -DskipTests

FROM eclipse-temurin:25-jre
WORKDIR /app
COPY --from=build /app/relay-processor/target/relay-processor-*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

